### ISSUE TITLE
单词拼写错了吧 ...

### ISSUE THREAD

**Issue by mark-lauq** [jeddygong/vite-plugin-progress#1]
https://github.com/jeddygong/vite-plugin-progress/blob/600d77237b1e6bd482ceee27ae9060d8b8c68ce1/src/index.ts#L66

~~Bouilding~~ `Building`

**Comment by jeddygong** [comment]
Thx

**Comment by jeddygong** [comment]
Fixed：[v0.0.2](https://github.com/jeddygong/vite-plugin-progress/releases/tag/v0.0.2)

Thx.
