### ISSUE TITLE
Warning: vite-plugin-progress@0.0.7: The engine "pnpm" appears to be invalid.

### ISSUE THREAD

**Issue by rijans** [jeddygong/vite-plugin-progress#11]
Hi, I am getting this warning message:

vite-plugin-progress@0.0.7: The engine "pnpm" appears to be invalid.

Is then pnpm "right" there? or I have mis-configured system?

**Comment by lvzhenbo** [comment]
This project requires [pnpm](https://github.com/pnpm/pnpm) as the package manager in [package.json](https://github.com/jeddygong/vite-plugin-progress/blob/main/package.json#L19)

**Comment by jeddygong** [comment]
Please use [pnpm version 7](https://pnpm.io/installation) or higher.
