### ISSUE TITLE
Cannot change `src` directory

### ISSUE THREAD

**Issue by czernika** [jeddygong/vite-plugin-progress#3]
Hi there!

I've got an error `no such file or directory, stat '/var/www/html/src'`. It's true - I have not this directory, but my source files are located in another directory (named `resources`), so I want to change path to it via config.

I guess, it hard-coded [here](https://github.com/jeddygong/vite-plugin-progress/blob/main/src/index.ts#L73), so maybe add configuration option like `srcDir` (will be `src` by default) or anything like this?

**Comment by jeddygong** [comment]
@czernika

First of all, thank you very much for your issues.

PR Welcome,
The source code is [here ](https://github.com/jeddygong/vite-plugin-progress/blob/main/src/index.ts#L73).

If you don't have PR, I will update it in Oct. 

Thx.

**Comment by jeddygong** [comment]
upgrade [v0.0.4](https://github.com/jeddygong/vite-plugin-progress/releases/tag/v0.0.4) @czernika
