### ISSUE TITLE
请问下 callback 什么时候执行

### ISSUE THREAD

**Issue by wzs28150** [jeddygong/vite-plugin-progress#5]
![f27404a3afb2b3bba3645a4399381c8](https://user-images.githubusercontent.com/21290257/192434202-930d475a-40e1-45f7-abac-10a130002756.jpg)
![image](https://user-images.githubusercontent.com/21290257/192434272-75b14e2c-d847-4d5c-9b96-21c0474285b6.png)
每次chunk一个就会执行一下 而且进度条没有把chunk的进度算在里面

**Comment by wzs28150** [comment]
好像是精度的问题 ，我的项目transorm 文件数过多chunk 过少， 然后进度条就直接 100% 了， 然后就会出现重复的多行 ，runCachedData里面的toFixed 我调成 toFixed(4) ，就不会出现多行问题，callback 这个方法是progress里面触发的吧， 是不是不到100%就不会出发？

**Comment by jeddygong** [comment]
> 

是的，在 100% 的时候就会正常触发回调，我在本地有用几千个 transform 的测试，并没有发现这个问题，但是我有加了个精度，它们可以正常运行；
upgrade [v0.0.5](https://github.com/jeddygong/vite-plugin-progress/releases/tag/v0.0.5) @wzs28150

**Comment by XYuanZ** [comment]
如何加精度的呀

**Comment by XYuanZ** [comment]
> 如何加精度的呀

可以了的，我升级了个包，think you
