### ISSUE TITLE
使用插件就报错，不使用可以正常打包

### ISSUE THREAD

**Issue by Tyh2001** [jeddygong/vite-plugin-progress#6]
## 描述

我在 [fighting-design](https://github.com/FightingDesign/fighting-design) 项目中使用了 `vite-plugin-progress`，使用插件打包就报错，不使用可以正常打包，报的是路径的错误。

## 错误截图

![56702529e373187ddd34f451ca43269](https://user-images.githubusercontent.com/73180970/196578667-a0f0ceaf-e9bc-4629-866a-fe312d4088fc.jpg)

## 复现步骤

- `clone` [fighting-design](https://github.com/FightingDesign/fighting-design)
- `pnpm i`
- `pnpm i vite-plugin-progress -D`
- 在 [vite.config.ts](https://github.com/FightingDesign/fighting-design/blob/master/vite.config.ts) 中添加：

```ts
import progress from 'vite-plugin-progress'

export default {
  plugins: [progress()],
}
```

- `pnpm build`

可以发现，使用插件之后打包报错，不使用的话就不会报错

**Comment by Tyh2001** [comment]
@jeddygong

**Comment by jeddygong** [comment]
@Tyh2001  
Hi, 因为打包入口默认是 src，由于你的是一个 monorepo，所以需要加一个 srcDir（[详见更多 options](https://github.com/jeddygong/vite-plugin-progress#options)），看起来就像下面的代码一样：
```ts
import progress from 'vite-plugin-progress'

export default {
  plugins: [
    progress({
      srcDir: 'packages/fighting-design'
    })
  ],
}

```
<img width="1110" alt="WX20221023-164234@2x" src="https://user-images.githubusercontent.com/64977484/197382915-531f726e-76b8-46cb-b4dc-63a50a524211.png">

**Comment by Tyh2001** [comment]
> @Tyh2001 Hi, 因为打包入口默认是 src，由于你的是一个 monorepo，所以需要加一个 srcDir（[详见更多 options](https://github.com/jeddygong/vite-plugin-progress#options)），看起来就像下面的代码一样：
> 
> ```ts
> import progress from 'vite-plugin-progress'
> 
> export default {
>   plugins: [
>     progress({
>       srcDir: 'packages/fighting-design'
>     })
>   ],
> }
> ```
> 
> <img alt="WX20221023-164234@2x" width="1110" src="https://user-images.githubusercontent.com/64977484/197382915-531f726e-76b8-46cb-b4dc-63a50a524211.png">

👍👍
