### ISSUE TITLE
无论打包成功与否 都会报build successful

### ISSUE THREAD

**Issue by liux4ever** [jeddygong/vite-plugin-progress#7]
如果打包失败应该怎么捕获错误并修改信息

**Comment by jeddygong** [comment]
可以提供对应的 demo 吗

**Comment by liux4ever** [comment]
因为有通过接口读取打包进度并返回的需求，所以需要知道打包成功或者失败。closeBound无论成功与否都会执行，因此打包失败仍然会输出 build successful.

目前我已经通过buildEnd钩子去捕获报错，作者可以考虑添加一下。

以下是测试demo
![image](https://user-images.githubusercontent.com/34912330/197427228-54eb0662-db16-4b64-8044-a0cdaa465c06.png)
![image](https://user-images.githubusercontent.com/34912330/197427257-ef8182bf-5be2-4a23-b9fb-16d9cd775898.png)

最终呈现结果
![image](https://user-images.githubusercontent.com/34912330/197427405-f8402984-aac1-4422-a82b-8fbdbcc5d182.png)

**Comment by jeddygong** [comment]
> 

Nice 👍
我后面空闲会去 fix；
当然 @liux4ever liu 要是有时间的话， pr welcome 😁

**Comment by liux4ever** [comment]
@jeddygong 好的，我尝试提交一下😁

**Comment by jeddygong** [comment]
@liux4ever liu Thx [PR](https://github.com/jeddygong/vite-plugin-progress/pull/8), fix [v0.0.6](https://github.com/jeddygong/vite-plugin-progress/releases/tag/v0.0.6)
